services:
  shoreside:
    image: mcschwartzman/webmoos-community:latest
    restart: "always"
    network_mode: host
    environment:
      SHORE_MPORT: 9000
      SHORE_PSHARE: 9200
      SHORE: localhost
    volumes:
      - ./community:/mnt/community
    entrypoint: ["/bin/bash", "-c", "/mnt/community/docker_2680.sh"]
  clayton:
    image: mcschwartzman/webmoos-community:latest
    restart: "always"
    network_mode: host
    environment:
      MPORT: 9001
      PSHARE: 9201
      VNAME: clayton
      VIP: localhost
      VROLE: rescue
      TMATE: mathew
      START_POS: "4,-7,135"
      SHORE: localhost
    volumes:
      - ./community:/mnt/community
    entrypoint: ["/bin/bash", "-c", "/mnt/community/docker_2680.sh"]

volumes:
  config: