# Configuration for Webmoos UI, API, and Shoreside

services:
  ui:
    build: ./ui
    restart: "always"
    ports:
      - 3000:3000
    networks:
      staticbridge:
        ipv4_address: 10.1.0.5
  api:
    build: ./api
    restart: "always"
    ports:
      - 8000:8000
    networks:
      staticbridge:
        ipv4_address: 10.1.0.3
  mqtt5:
    image: eclipse-mosquitto
    ports:
      - 1883:1884/tcp #default mqtt port exposed out
      - 9901:9901/tcp #default mqtt port for websockets
    # network_mode: host
    volumes:
      - ./config:/mosquitto/config:rw
    #   - ./data:/mosquitto/data:rw
    #   - ./log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      staticbridge:
        ipv4_address: 10.1.0.4
  shoreside:
    build: ./autonomy
    restart: "always"
    ports:
      - 9000:9000
    networks:
      staticbridge:
        ipv4_address: 10.1.0.2
    environment:
      MPORT: 9000
      PSHARE: 9200
    volumes:
      - ../moos-ivp-2680:/git/moos-ivp-2680
    env_file:
      - path: ./globals.env
        required: true
  clayton:
    build: ./autonomy
    restart: "always"
    ports:
      - 9001:9001
    networks:
      staticbridge:
        ipv4_address: 10.1.0.21
    environment:
      MPORT: 9001
      PSHARE: 9201
      VNAME: clayton
      VIP: 10.1.0.21
      VROLE: rescue
      TMATE: mathew
      EXTENDBIN: /git/moos-ivp-cdembski/bin
      EXTENDLIB: /git/moos-ivp-2680/lib
      START_POS: "4,-7,135"
    volumes:
      - ../moos-ivp-2680:/git/moos-ivp-2680
      - ../moos-ivp-cdembski:/git/moos-ivp-cdembski
    env_file:
      - path: ./globals.env
        required: true
  mathew:
    build: ./autonomy
    restart: "always"
    ports:
      - 9002:9002
    networks:
      staticbridge:
        ipv4_address: 10.1.0.22
    environment:
      MPORT: 9002
      PSHARE: 9202
      VNAME: mathew
      VIP: 10.1.0.22
      VROLE: scout
      TMATE: clayton
      IVP_BEHAVIOR_DIRS: /git/moos-ivp-mcschwar/lib
      EXTENDBIN: /git/moos-ivp-mcschwar/bin
      EXTENDLIB: /git/moos-ivp-mcschwar/lib
      START_POS: "-12,-15,135"
    volumes:
      - ../moos-ivp-mcschwar:/git/moos-ivp-mcschwar
      - ../moos-ivp-2680:/git/moos-ivp-2680
    env_file:
      - path: ./globals.env
        required: true
  jeremy:
    build: ./autonomy
    restart: "always"
    ports:
      - 9003:9003
    networks:
      staticbridge:
        ipv4_address: 10.1.0.23
    environment:
      MPORT: 9003
      PSHARE: 9203
      VNAME: jeremy
      VIP: 10.1.0.23
      VROLE: rescue
      TMATE: josh
      IVP_BEHAVIOR_DIRS: /git/moos-ivp-2680/lib
      BASE: "true"
      EXTENDBIN: /git/moos-ivp-mcschwar/bin
      EXTENDLIB: /git/moos-ivp-2680/lib
      START_POS: "-23,-20,135"
    volumes:
      - ../moos-ivp-2680:/git/moos-ivp-2680
      - ../moos-ivp-mcschwar:/git/moos-ivp-mcschwar
    env_file:
      - path: ./globals.env
        required: true
  josh:
    build: ./autonomy
    restart: "always"
    ports:
      - 9004:9004
    networks:
      staticbridge:
        ipv4_address: 10.1.0.24
    environment:
      MPORT: 9004
      PSHARE: 9204
      VNAME: josh
      VIP: 10.1.0.24
      VROLE: scout
      TMATE: jeremy
      IVP_BEHAVIOR_DIRS: /git/moos-ivp-2680/lib
      BASE: "true"
      EXTENDBIN: /git/moos-ivp-2680/bin
      EXTENDLIB: /git/moos-ivp-2680/lib
      START_POS: "-34,-24,135"
    volumes:
      - ../moos-ivp-2680:/git/moos-ivp-2680
    env_file:
      - path: ./globals.env
        required: true

volumes:
  config:

networks:
  staticbridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1