services:
  shoreside:
    image: mcschwartzman/webmoos-community-arm:latest
    restart: "always"
    environment:
      SHORE_MPORT: 9000
      SHORE_PSHARE: 9200
      SHORE: 10.1.0.2
    ports:
      - "9000:9000/tcp"
    networks:
      staticbridge:
        ipv4_address: 10.1.0.2
    volumes:
      - ./community/missions:/mnt/community/missions
    entrypoint: ["/bin/bash", "-c", "/docker_2680.sh"]
  clayton:
    image: mcschwartzman/webmoos-community-arm:latest
    restart: "always"
    environment:
      MPORT: 9001
      PSHARE: 9201
      VNAME: clayton
      VIP: 10.1.0.21
      VROLE: rescue
      TMATE: mathew
      START_POS: "4,-7,135"
      SHORE: 10.1.0.2
    ports:
      - "9001:9001/tcp"
    networks:
      staticbridge:
        ipv4_address: 10.1.0.21
    volumes:
      - ./community/missions:/mnt/community/missions
    entrypoint: ["/bin/bash", "-c", "/docker_2680.sh"]

volumes:
  config:
  
networks:
  staticbridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1