# Configuration for Webmoos UI, API, and Shoreside

services:
  shoreside:
    build: ./autonomy
    restart: "always"
    ports:
      - 9000:9000
    networks:
      staticbridge:
        ipv4_address: 10.1.0.2
    environment:
      TIMEWARP: "10"
      MPORT: 9000
      PSHARE: 9200
    volumes:
      - ../moos-ivp-mcschwar:/git/moos-ivp-mcschwar
      - ../moos-ivp-2680:/git/moos-ivp-2680
  henry:
    build: ./autonomy
    restart: "always"
    ports:
      - 9001:9001
    networks:
      staticbridge:
        ipv4_address: 10.1.0.21
    environment:
      TIMEWARP: "10"
      MPORT: 9001
      PSHARE: 9201
      VNAME: henry
      VIP: 10.1.0.21
      VROLE: rescue
      TMATE: gilda
    volumes:
      - ../moos-ivp-mcschwar:/git/moos-ivp-mcschwar
      - ../moos-ivp-2680:/git/moos-ivp-2680
  gilda:
    build: ./autonomy
    restart: "always"
    ports:
      - 9002:9002
    networks:
      staticbridge:
        ipv4_address: 10.1.0.22
    environment:
      TIMEWARP: "10"
      MPORT: 9002
      PSHARE: 9202
      VNAME: gilda
      VIP: 10.1.0.22
      VROLE: scout
      TMATE: henry
      IVP_BEHAVIOR_DIRS: /git/moos-ivp-mcschwar/lib
    volumes:
      - ../moos-ivp-mcschwar:/git/moos-ivp-mcschwar
      - ../moos-ivp-2680:/git/moos-ivp-2680
  api:
    build: ./api
    restart: "always"
    ports:
      - 8000:8000
    networks:
      staticbridge:
        ipv4_address: 10.1.0.3
  mqtt5:
    image: eclipse-mosquitto
    ports:
      - 1883:1884/tcp #default mqtt port exposed out
    # network_mode: host
    volumes:
      - ./config:/mosquitto/config:rw
    #   - ./data:/mosquitto/data:rw
    #   - ./log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      staticbridge:
        ipv4_address: 10.1.0.4
  ui:
    build: ./ui
    restart: "always"
    ports:
      - 3000:3000
    networks:
      staticbridge:
        ipv4_address: 10.1.0.5

volumes:
  config:

networks:
  staticbridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1