apiVersion: v1
data:
  .LastOpenedMOOSLogDirectory: |
    LastOpenedLoggingDirectory=./MOOSLog_17_2_2025_____11_21_33
  .gitignore: |
    ## 1 - C++

    # Prerequisites
    *.d

    # Compiled Object files
    *.slo
    *.lo
    *.o
    *.obj

    # Precompiled Headers
    *.gch
    *.pch

    # Compiled Dynamic libraries
    *.so
    *.dylib
    *.dll

    # Fortran module files
    *.mod
    *.smod

    # Compiled Static libraries
    *.lai
    *.la
    *.a
    *.lib

    # Executables
    *.exe
    *.out
    *.app


    ## 2 - MOOS

    # Log files
    *.alog
    *.blog
    *.ylog
    *.klog
    *.moos++
    *._moos
    *._bhv
    targ_*
    .LastOpenedMOOSLogDirectory
    **/.LastOpenedLoggingDirectory
    MOOSLog*/
    Log*/
    XLog*/

    # Build dirs
    build/
    bin/
    lib/

    # Temp files (emacs, etc)
    *#
    *~
  CMakeLists.txt: "#=======================================================================\n# FILE:  moos-ivp-extend/CMakeLists.txt\n# DATE:  2012/07/24\n# INFO:  Top-level CMakeLists.txt file for the moos-ivp-extend project\n# NAME:  Maintained by Mike Benjamin - Original setup by Christian Convey\n#        Chris Gagner, and tips borrowed from Dave Billin\n#=======================================================================\n\nCMAKE_MINIMUM_REQUIRED(VERSION 3.0)\nPROJECT( IVP_EXTEND )\n\nset (CMAKE_CXX_STANDARD 11)\n\n#=======================================================================\n# Set the output directories for the binary and library files\n#=======================================================================\n\nGET_FILENAME_COMPONENT(IVP_EXTEND_BIN_DIR \"${CMAKE_SOURCE_DIR}/bin\"  ABSOLUTE )\nGET_FILENAME_COMPONENT(IVP_EXTEND_LIB_DIR \"${CMAKE_SOURCE_DIR}/lib\"  ABSOLUTE )\n\nSET( LIBRARY_OUTPUT_PATH      \"${IVP_EXTEND_LIB_DIR}\" CACHE PATH \"\" )\nSET( ARCHIVE_OUTPUT_DIRECTORY \"${IVP_EXTEND_LIB_DIR}\" CACHE PATH \"\" )\nSET( LIBRARY_OUTPUT_DIRECTORY \"${IVP_EXTEND_LIB_DIR}\" CACHE PATH \"\" )\n\nSET( EXECUTABLE_OUTPUT_PATH    \"${IVP_EXTEND_BIN_DIR}\" CACHE PATH \"\" )\nSET( RUNTIME_OUTPUT_DIRECTORY \"${IVP_EXTEND_BIN_DIR}\"  CACHE PATH \"\" )\n\n#=======================================================================\n# Find MOOS\n#=======================================================================\nfind_package(MOOS 10.0)\nINCLUDE_DIRECTORIES(${MOOS_INCLUDE_DIRS})\n\n#=======================================================================\n# Find the \"moos-ivp\" base directory\n#=======================================================================\n\n# Search for the moos-ivp folder\nfind_path( MOOSIVP_SOURCE_TREE_BASE\n           NAMES build-ivp.sh build-moos.sh configure-ivp.sh\n           PATHS \"../moos-ivp\" \"../../moos-ivp\" \"../../moos-ivp/trunk/\" \"../moos-ivp/trunk/\"\n           DOC \"Base directory of the MOOS-IvP source tree\"\n           NO_DEFAULT_PATH\n)\n\nif (NOT MOOSIVP_SOURCE_TREE_BASE)\n    message(\"Please set MOOSIVP_SOURCE_TREE_BASE to  \")\n    message(\"the location of the \\\"moos-ivp\\\" folder \")\n    message( FATAL_ERROR \"CMake will exit.\" )\nendif()\n\n#======================================================================\n# Specify where to find IvP's headers and libraries...\n#======================================================================\n\nFILE(GLOB IVP_INCLUDE_DIRS ${MOOSIVP_SOURCE_TREE_BASE}/ivp/src/lib_* )\nINCLUDE_DIRECTORIES(${IVP_INCLUDE_DIRS})\n\nFILE(GLOB IVP_LIBRARY_DIRS ${MOOSIVP_SOURCE_TREE_BASE}/lib )\nLINK_DIRECTORIES(${IVP_LIBRARY_DIRS})\n\n#======================================================================\n# Specify Compiler Flags\n#======================================================================\nIF( ${WIN32} )\n   #---------------------------------------------\n   # Windows Compiler Flags\n   #---------------------------------------------\n   IF(MSVC)\n      # Flags for Microsoft Visual Studio\n      SET( WALL_ON OFF CACHE BOOL \n         \"tell me about all compiler warnings (-Wall) \")\n      IF(WALL_ON)\n         SET(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -Wall\")\n      ENDIF(WALL_ON)\n   ELSE(MSVC)\n      # Other Windows compilers go here\n   ENDIF(MSVC)\n\nELSE( ${WIN32} )\n   #---------------------------------------------\n   # Linux and Apple Compiler Flags\n   #---------------------------------------------\n   # Force -fPIC because gcc complains when we don't use it with x86_64 code.\n   # Note sure why: -fPIC should only be needed for shared objects, and\n   # AFAIK, CMake gets that right when building shared objects. -CJC\n   SET(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -fPIC -g -Wdeprecated-declarations\")\n   IF(CMAKE_COMPILER_IS_GNUCXX)\n      # Flags for the GNU C++ Compiler\n      SET( WALL_ON OFF CACHE BOOL \n         \"tell me about all compiler warnings (-Wall) \")\n      IF(WALL_ON)\n         SET(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -Wall\" -C++11)\n      ENDIF( WALL_ON)\n   ELSE(CMAKE_COMPILER_IS_GNUCXX)\n    \n   ENDIF(CMAKE_COMPILER_IS_GNUCXX)\n\nENDIF( ${WIN32} )\n\n#=======================================================================\n# Add Subdirectories\n#=======================================================================\nADD_SUBDIRECTORY( src )\n"
  README: "##############################################################################\n# FILE:        moos-ivp-extend/README\n# DATE:        2014/01/02\n# DESCRIPTION: Contains important information regarding the moos-ivp-extend\n#              repository.\n##############################################################################\n\n#=============================================================================\n# Introduction\n#=============================================================================\nThe moos-ivp-extend repository contains examples for extending the MOOS-IvP\nAutonomy system. This includes a MOOS application and an IvP behavior.\n\n\n#=============================================================================\n# Directory Structure\n#=============================================================================\nThe directory structure for the moos-ivp-extend is decribed below:\n\nbin              - Directory for generated executable files\nbuild            - Directory for build object files\nbuild.sh         - Script for building moos-ivp-extend\nCMakeLists.txt   - CMake configuration file for the project\ndata             - Directory for storing data\nlib              - Directory for generated library files\nmissions         - Directory for mission files\nREADME           - Contains helpful information - (this file).\nscripts          - Directory for script files\nsrc              - Directory for source code\n\n\n#=============================================================================\n# Build Instructions\n#=============================================================================\n#--------------------\n# Linux and Mac Users\n#--------------------\n\nTo build on Linux and Apple platforms, execute the build script within this\ndirectory:\n\n   $ ./build.sh\n\nTo build without using the supplied script, execute the following commands\nwithin this directory:\n\n   $ mkdir -p build\n   $ cd build\n   $ cmake ../\n   $ make\n   $ cd ..\n\n\n#--------------\n# Windows Users\n#--------------\nTo build on Windows platform, open CMake using your favorite shortcut. Then \nset the source directory to be this directory and set the build directory\nto the \"build\" directory inside this directory.\n\nThe source directory is typically next to the question:\n   \"Where is the source code?\"\n\nThe build directory is typically next to the question:\n   \"Where to build the binaries?\"\n\nAlternatively, CMake can be invoked via the command line. However, you must\nspecify your gernerator. Use \"cmake --help\" for a list of generators and\nadditional help.\n\n#=============================================================================\n# Environment variables\n#=============================================================================\nThe moos-ivp-extend binaries files should be added to your path to allow them\nto be launched from pAntler. \n\nIn order for generated IvP Behaviors to be recognized by the IvP Helm, you\nshould add the library directory to the \"IVP_BEHAVIOR_DIRS\" environment \nvariable.\n\n##############################################################################\n#                               END of README\n##############################################################################\n\n"
  README.md: |+
    # moos-ivp-extend

    |              |                        |
    |:------------ |:---------------------- |
    | FILE:        | moos-ivp-extend/README |
    | DATE:        | 2014/01/02             |
    | DESCRIPTION: | Contains important information regarding the moos-ivp-extend repository. |


    # Introduction

    The moos-ivp-extend repository contains examples for extending the MOOS-IvP
    Autonomy system. This includes a MOOS application and an IvP behavior.


    # Directory Structure

    The directory structure for the moos-ivp-extend is described below:

    | Directory        | Description                                 |
    |:---------------- |:------------------------------------------- |
    | bin              | Directory for generated executable files    |
    | build            | Directory for build object files            |
    | build.sh         | Script for building moos-ivp-extend         |
    | CMakeLists.txt   | CMake configuration file for the project    |
    | data             | Directory for storing data                  |
    | lib              | Directory for generated library files       |
    | missions         | Directory for mission files                 |
    | README           | Contains helpful information - (this file). |
    | scripts          | Directory for script files                  |
    | src              | Directory for source code                   |


    # Build Instructions

    ## Linux and Mac Users

    To build on Linux and Apple platforms, execute the build script within this
    directory:

    ```bash
       $ ./build.sh
    ```

    To build without using the supplied script, execute the following commands
    within this directory:

    ```bash
       $ mkdir -p build
       $ cd build
       $ cmake ../
       $ make
       $ cd ..
    ```


    ## Windows Users

    To build on Windows platform, open CMake using your favorite shortcut. Then
    set the source directory to be this directory and set the build directory
    to the "build" directory inside this directory.

    The source directory is typically next to the question:
       "Where is the source code?"

    The build directory is typically next to the question:
       "Where to build the binaries?"

    Alternatively, CMake can be invoked via the command line. However, you must
    specify your generator. Use "cmake --help" for a list of generators and
    additional help.


    # Environment variables

    The moos-ivp-extend binaries files should be added to your path to allow them
    to be launched from pAntler.

    In order for generated IvP Behaviors to be recognized by the IvP Helm, you
    should add the library directory to the "IVP_BEHAVIOR_DIRS" environment
    variable.

    # END of README

  build.sh: "#!/bin/bash\n\nINVOCATION_ABS_DIR=`pwd`\nBUILD_TYPE=\"None\"\nCMD_LINE_ARGS=\"\"\n\n#-------------------------------------------------------------------\n#  Part 1: Check for and handle command-line arguments\n#-------------------------------------------------------------------\nfor ARGI; do\n    if [ \"${ARGI}\" = \"--help\" -o \"${ARGI}\" = \"-h\" ] ; then\n\tprintf \"%s [SWITCHES]                       \\n\" $0\n\tprintf \"Switches:                           \\n\" \n\tprintf \"  --help, -h                        \\n\" \n        printf \"  --debug,   -d                     \\n\"\n        printf \"  --release, -r                     \\n\"\n\tprintf \"Notes:                              \\n\"\n\tprintf \" (1) All other command line args will be passed as args    \\n\"\n\tprintf \"     to \\\"make\\\" when it is eventually invoked.            \\n\"\n\tprintf \" (2) For example -k will continue making when/if a failure \\n\"\n\tprintf \"     is encountered in building one of the subdirectories. \\n\"\n\tprintf \" (3) For example -j2 will utilize a 2nd core in the build  \\n\"\n\tprintf \"     if your machine has two cores. -j4 etc for quad core. \\n\"\n\texit 0;\n    elif [ \"${ARGI}\" = \"--debug\" -o \"${ARGI}\" = \"-d\" ] ; then\n        BUILD_TYPE=\"Debug\"\n    elif [ \"${ARGI}\" = \"--release\" -o \"${ARGI}\" = \"-r\" ] ; then\n        BUILD_TYPE=\"Release\"\n    else\n\tCMD_LINE_ARGS=$CMD_LINE_ARGS\" \"$ARGI\n    fi\ndone\n\n#-------------------------------------------------------------------\n#  Part 2: Invoke the call to make in the build directory\n#-------------------------------------------------------------------\n\nmkdir -p build\ncd build\n\ncmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ../ || exit 1\n\nmake ${CMD_LINE_ARGS}\ncd ${INVOCATION_ABS_DIR}\n\n\n"
  clean.sh: |+
    #!/bin/bash

    rm -rf build/*
    rm -rf lib/*
    rm -rf bin/p*
    rm -f .DS_Store
    rm -f  missions/*/.LastOpenedMOOSLogDirectory

    find . -name '.DS_Store'  -print -exec rm -rfv {} \;
    find . -name '*~'  -print -exec rm -rfv {} \;
    find . -name '#*'  -print -exec rm -rfv {} \;
    find . -name '*.moos++'  -print -exec rm -rfv {} \;

    find . -name 'MOOSLog*'  -print -exec rm -rfv {} \;

  trying123.txt: |2
    hey there
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: clayton
  name: clayton-cm1
