apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.mathew.yaml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: jeremy
  name: jeremy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jeremy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.mathew.yaml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: jeremy
    spec:
      containers:
        - env:
            - name: BASE
              value: "true"
            - name: EXTENDBIN
              value: /git/moos-ivp-2680/bin:/git/moos-ivp-mcschwar/bin
            - name: EXTENDLIB
              value: /git/moos-ivp-2680/lib
            - name: IVP_BEHAVIOR_DIRS
              value: /git/moos-ivp-2680/lib
            - name: MPORT
              value: "9003"
            - name: PSHARE
              value: "9203"
            - name: START_POS
              value: -23,-20,135
            - name: TMATE
              value: josh
            - name: VIP
              value: 10.1.0.23
            - name: VNAME
              value: jeremy
            - name: VROLE
              value: rescue
          envFrom:
            - configMapRef:
                name: globals-env
          image: jeremy
          name: jeremy
          ports:
            - containerPort: 9003
              protocol: TCP
          volumeMounts:
            - mountPath: /git/moos-ivp-2680
              name: jeremy-cm0
            - mountPath: /git/moos-ivp-mcschwar
              name: jeremy-cm1
      restartPolicy: Always
      volumes:
        - configMap:
            name: jeremy-cm0
          name: jeremy-cm0
        - configMap:
            name: jeremy-cm1
          name: jeremy-cm1
