apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.mathew.yaml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: jeremy
  name: jeremy
spec:
  ports:
    - name: "9003"
      port: 9003
      targetPort: 9003
  selector:
    io.kompose.service: jeremy
