apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.mathew.yaml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: mathew
  name: mathew
spec:
  ports:
    - name: "9002"
      port: 9002
      targetPort: 9002
  selector:
    io.kompose.service: mathew
