apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.mathew.yaml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: shoreside
  name: shoreside
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: shoreside
